submit_slogan:
  path: /api/slogan
  methods:
    - POST
  defaults:
    _controller: ContestApplicationBundle:Slogan:submit

list_slogans:
  path: /api/slogans
  methods:
    - GET
  defaults:
    _controller: ContestApplicationBundle:Slogan:list