services:
    contest_application.slogan_factory:
        class: "Contest\ApplicationBundle\Entity\SloganFactory"
    contest_application.slogan_gateway:
        class: "Contest\ApplicationBundle\Entity\SloganGateway"
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ContestApplicationBundle:Slogan]
    contest_application.slogan_repository:
        class: "Contest\ApplicationBundle\Entity\SloganRepository"
        arguments: [@contest_application.slogan_gateway, @contest_application.slogan_factory]

